# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
    tasks: ["test", "connectedAndroidTest"],
    properties: {
          "coverage" => "true"
        }
    )
  end

  desc "Increment version code"
   lane :increment_vc do
     increment_version_code(
         gradle_file_path: "./app/build.gradle",
     )
  end

  desc "Build release app bundle"
  lane :build_apk do
    gradle(task: "clean assembleRelease")
  end

  desc "Test, Build and Deploy a new version"
  lane :deploy do
     test
     # The lane you created previously to increment your app’s `version code`.
     increment_vc
     # The build release apk lane you created previously.
     build_apk
  end
end
